Adding options to deploy Promitor with managed identity
promitor/charts pull request #36
Opened 2021-03-08 14:08 UTC by Mimetis

# Adding options to authenticate Promitor using Managed Identity

Update of the charts (Scraper and Resource-Discovery) to allow user to authenticate Promitor with Managed Identity

Basically, in both charts, `values.yaml`, `configmap.yaml`, `deployment.yaml`, and `secret.yaml` have been updated.

From a user perspective, here is a sample of a `values.yaml` that can be submitted:

Using a **Service Principal**:
``` yaml
azureAuthentication:
  appId: "xxxxxxxx-xxxxx-xxxxxx-xxxxxx"
  appKey: "xxxxxxxx-xxxxx-xxxxxx-xxxxxx"
  mode: "servicePrincipal"
```

Using a **Service Managed Identity** (with aad pod indentity already deployed in the aks cluster):
``` yaml
azureAuthentication:
  mode: "managedIdentity"
  aadpodidbinding: "xxxxxxxxxx"
```

Using a **User Managed Identity**:
``` yaml
azureAuthentication:
  managedIdentityId: "xxxxxxxx-xxxxx-xxxxxx-xxxxxx"
  mode: "managedIdentity"
```

*Note* : If `mode` is not specified, the `servicePrincipal` value is used by default.

2021-03-08 14:08 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/promitor/charts?pullRequest=36) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/promitor/charts?pullRequest=36) before we can accept your contribution.<br/><hr/>**sebastien.pertus** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/promitor/charts?pullRequest=36) it.</sub>

2021-03-08 15:13 UTC, tomkerkhove commented
Thanks for the PR! Let's put this PR on hold until https://github.com/tomkerkhove/promitor/pull/1544 is finished

2021-03-30 17:28 UTC, tomkerkhove reviewed
Are you able to update this to the recent changes or do you prefer if I pick this up?

2021-03-30 17:28 UTC, tomkerkhove commented on promitor-agent-resource-discovery/values.yaml
> +  aadpodidbinding: ""
I'd love to use this approach instead:
```suggestion
  mode: "ServicePrincipal"
  identity
    id: ""
    key: ""
    binding
```

2021-03-30 17:59 UTC, Mimetis commented
No worry, I'll do it !

2021-03-31 16:28 UTC, Mimetis commented on promitor-agent-resource-discovery/values.yaml
> +  aadpodidbinding: ""
Sounds good to me

2021-04-01 15:31 UTC, tomkerkhove requested changes
LGTM, just a few small remarks to be backwards compatible

2021-04-01 15:31 UTC, tomkerkhove commented on promitor-agent-resource-discovery/values.yaml
> -  appKey:
We'll have to be backward compatible here where the new one is favored over the old one; but we shouldn't break the current experience.

2021-04-01 15:31 UTC, tomkerkhove commented on promitor-agent-scraper/values.yaml
> -  appKey: ""
We'll have to be backward compatible here where the new one is favored over the old one; but we shouldn't break the current experience.

2021-04-01 15:31 UTC, tomkerkhove commented on promitor-agent-resource-discovery/README.md
> -| `azureAuthentication.appKey`  | Secret of the Azure AD entity to authenticate with |             |
We'll have to be backward compatible here where the new one is favored over the old one; but we shouldn't break the current experience.

We can thus keep this but mark it as deprecated with reference to new appraoch

2021-04-01 15:31 UTC, tomkerkhove commented on promitor-agent-scraper/README.md
> -| `azureAuthentication.appKey`  | Secret of the Azure AD entity to authenticate with |             |
We'll have to be backward compatible here where the new one is favored over the old one; but we shouldn't break the current experience.

We can thus keep this but mark it as deprecated with reference to new appraoch

2021-04-01 15:31 UTC, tomkerkhove commented on promitor-agent-scraper/README.md
> +               --set azureAuthentication.identity.id='<azure-ad-app-id>' \
Just to be complete
```suggestion
               --set azureAuthentication.identity.mode='ServicePrincipal' \
               --set azureAuthentication.identity.id='<azure-ad-app-id>' \
```

2021-04-01 15:31 UTC, tomkerkhove commented on promitor-agent-resource-discovery/README.md
> +               --set azureAuthentication.identity.id='<azure-ad-app-id>' \
Just to be complete
```suggestion
               --set azureAuthentication.identity.mode='ServicePrincipal' \
               --set azureAuthentication.identity.id='<azure-ad-app-id>' \
```

2021-04-02 08:56 UTC, tomkerkhove approved these changes
LGTM, thank you a lot @Mimetis!

2021-04-02 08:56 UTC, tomkerkhove commented on promitor-agent-resource-discovery/values.yaml
> +  mode: "servicePrincipal"
```suggestion
  mode: "ServicePrincipal"
```

2021-04-02 08:56 UTC, tomkerkhove commented on promitor-agent-scraper/templates/configmap.yaml
> +        mode: {{ .Values.azureAuthentication.mode | default "servicePrincipal"}}
```suggestion
        mode: {{ .Values.azureAuthentication.mode | default "ServicePrincipal"}}
```

2021-04-02 08:56 UTC, tomkerkhove commented on promitor-agent-resource-discovery/templates/configmap.yaml
> +        mode: {{ .Values.azureAuthentication.mode | default "servicePrincipal"}}
```suggestion
        mode: {{ .Values.azureAuthentication.mode | default "ServicePrincipal"}}
```

2021-04-02 08:56 UTC, tomkerkhove commented on promitor-agent-scraper/values.yaml
> +  mode: "servicePrincipal"
```suggestion
  mode: "ServicePrincipal"
```

2021-04-02 09:24 UTC, merged

2021-05-26 02:51 UTC, locmai commented
Hi @Mimetis @tomkerkhove  , I have tried resource discovery chart and got authenticated with aadpodbinding for a Us Gov cloud subscription: 
<img width="577" alt="Screen Shot 2021-05-26 at 09 46 37" src="https://user-images.githubusercontent.com/27542393/119595204-61376180-be07-11eb-8ff6-10940e80bd1a.png">

But when I tried the health check api with the `api/v1/health?includeDependencies=true` and got this:
```
Unable to discover resources due to an unexpected exception: Operation returned an invalid status code 'Unauthorized'
Microsoft.Azure.Management.ResourceGraph.Models.ErrorResponseException: Operation returned an invalid status code 'Unauthorized'
at Microsoft.Azure.Management.ResourceGraph.ResourceGraphClient.ResourcesWithHttpMessagesAsync(QueryRequest query, Dictionary`2 customHeaders, CancellationToken cancellationToken)
at Microsoft.Azure.Management.ResourceGraph.ResourceGraphClientExtensions.ResourcesAsync(IResourceGraphClient operations, QueryRequest query, CancellationToken cancellationToken)
at Promitor.Agents.ResourceDiscovery.Graph.AzureResourceGraph.<>c__DisplayClass13_0.<<QueryAsync>b__0>d.MoveNext() in /src/Promitor.Agents.ResourceDiscovery/AzureResourceGraph.cs:line 80
--- End of stack trace from previous location where exception was thrown ---
at Promitor.Agents.ResourceDiscovery.Graph.AzureResourceGraph.<>c__DisplayClass14_0`1.<<InteractWithAzureResourceGraphAsync>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at Polly.Retry.AsyncRetryEngine.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Func`5 onRetryAsync, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider, Boolean continueOnCapturedContext)
at Polly.AsyncPolicy.ExecuteAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)
at Promitor.Agents.ResourceDiscovery.Graph.AzureResourceGraph.InteractWithAzureResourceGraphAsync[TResponse](String queryName, String query, List`1 targetSubscriptions, Func`2 interactionFunc) in /src/Promitor.Agents.ResourceDiscovery/AzureResourceGraph.cs:line 93
at Promitor.Agents.ResourceDiscovery.Graph.AzureResourceGraph.QueryAsync(String queryName, String query, List`1 targetSubscriptions) in /src/Promitor.Agents.ResourceDiscovery/AzureResourceGraph.cs:line 77
at Promitor.Agents.ResourceDiscovery.Graph.AzureResourceGraph.QueryForResourcesAsync(String queryName, String query, List`1 targetSubscriptions) in /src/Promitor.Agents.ResourceDiscovery/AzureResourceGraph.cs:line 67
at Promitor.Agents.ResourceDiscovery.Health.AzureResourceGraphHealthCheck.ProbeSubscriptionAsync(String query, String subscription) in /src/Promitor.Agents.ResourceDiscovery/AzureResourceGraphHealthCheck.cs:line 84
```

Is there any known issue with Us Gov cloud running with aadpodidentity? 

P/S: I have checked the identity (with Reader and even Contributor role for the subscription) with azure-cli and I could fetch everything.

2021-05-26 06:00 UTC, tomkerkhove commented
Thanks for letting me know, would you mind opening a discussion for this please? I'll then take a look!